### ISSUE TITLE
Positive (Happy Path) Test Coverage of Credential Revocation

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#102]
AS AN Issuer, I WANT to be able to revoke an issued credential, SO THAT holders can't continue to prove claims from the credential if it was replaced by an updated version, issued in error, or the holder did something "bad" to warrant they no longer qualify to hold said credential.

### Acceptance Criteria
Scenario: Credential revoked by Issuer and Holder attempts to prove
Scenario: Credential revoked and replaced with a new updated credential, holder proves claims with the updated credential
Scenario (Neg): Proof in process while Issuer revokes credential before presentation
Scenario (Neg): Credential revoked and replaced with a new updated credential, holder proves claims with the updated credential but presents the revoked credential

### References & Source Documents
[0011 Credential Revocation](https://github.com/hyperledger/indy-hipe/tree/master/text/0011-cred-revocation)
[Revocation Registry Handling in ACA-Py](https://hackmd.io/_BYKvL71T3W4ECele9BZuQ)
[RFC 0183 Revocation Notification 1.0](https://github.com/hyperledger/aries-rfcs/tree/master/features/0183-revocation-notification)
[Implement revocation registry support for credential issuance](https://app.zenhub.com/workspaces/von---verifiable-organization-network-5adf53987ccbaa70597dbec0/issues/hyperledger/aries-cloudagent-python/146)
[ACA-Py Admin endpoint for revoking a credential](https://app.zenhub.com/workspaces/von---verifiable-organization-network-5adf53987ccbaa70597dbec0/issues/hyperledger/aries-cloudagent-python/428)
[Evolve the handling of revocation registries into ACA-Py and away from the controller](https://app.zenhub.com/workspaces/von---verifiable-organization-network-5adf53987ccbaa70597dbec0/issues/hyperledger/aries-cloudagent-python/545)
[Revoked credential](https://app.zenhub.com/workspaces/von---verifiable-organization-network-5adf53987ccbaa70597dbec0/issues/hyperledger/aries-cloudagent-python/650)
[Question: how revocation works?](https://github.com/hyperledger/aries-cloudagent-python/issues/505)

### Action Items

- [x] Get experts in the protocol and research references to identify and define the BDD test cases and document them in the Acceptance Criteria and feature file
- [x] Implement the test steps for the BDD Test Cases
- [x] Define the backchannel API calls necessary to support the test functions.
- [x] Implement capabilities in the ACA-Py backchannel controller to enable execution of the tests where both agents are ACA-Py
- [x] Document Coverage in the Test Coverage Matrix

**Comment by swcurran** [comment]
Adjusted the use case a little to reflect what revocation does and when it is used.  The most common use case is likely to just be "because there was an update to the data".

**Comment by nodlesh** [comment]
#141
