### ISSUE TITLE
No such container: bob_agent

### ISSUE THREAD

**Issue by TheArhaam** [openwallet-foundation/owl-agent-test-harness#104]
While I was following [these steps](https://github.com/hyperledger/aries-agent-test-harness#aries-agent-test-harness-smashing-complexity-in-interoperability-testing) in play-with-docker, I ran into this error:
`Error: No such container: bob_agent`

**Comment by swcurran** [comment]
I was on Play with Docker yesterday and they were having trouble - might be an issue with that.  The demo you are running is a basic demo of the repo, so perhaps it was an intermittent issue.  I've just run the tests and all is working.

**Comment by TheArhaam** [comment]
@swcurran Alright I'll try running it in docker on my system once and see if I'm able to get it to run. Thank you 😄

**Comment by TheArhaam** [comment]
@swcurran It seems to work perfectly on my system, I guess you were right, Play with Docker is probably facing some issues. Thank you so much 😄
