### ISSUE TITLE
Accessible Hosting of the Allure Docker Containers for AATH running in Build Pipeline

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#118]
AS Quality Assurance & Dev Ops, I WANT to access allure reports from Aries Agent Test Harness test execution running in the build pipeline perpetually, SO THAT the Test execution engine can be sure there is a reporting service to send results to for every daily run. 

#### Description
To get the Allure docker related files:
```
git clone https://github.com/nodlesh/aries-agent-test-harness.git
cd aries-agent-test-harness/aries-test-harness/allure
```

There are two containers to instantiate and keep running. Allure; which is the main service to serve reports to the public and handle report generation, and allure-ui; which is just an admin ui on all the services allure provides. 
To instantiate those containers:
```sh
docker-compose up -d allure 
docker-compose up -d allure-ui
```

The `docker-compose.yml` will need to be updated to point allure-ui to the of the allure service (the allure container) host.
```
environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
``` 

- Verify if Allure API is working. Go to -> http://host:5050/allure-docker-service/latest-report

- Verify if Allure UI is working. Go to -> http://host:5252/allure-docker-service-ui/

Let @nodlesh know the Host for the URLs above. 

---
##### Security & Authentication
The following will need to be investigated before implementation.
The Allure UI may need to be secured.  this would be done through basic authentication. Note there should be no need to secure the allure service. Access to the reports should be open. 

If it is deemed necessary to secure both the UI and the Service we can use Allure internal security to do this. We would need to change the docker compose xml file in the allure folder to include
```
    environment:
      SECURITY_USER: "my_username"
      SECURITY_PASS: "my_password"
      SECURITY_ENABLED: 1
```
Allure Docker Service's security features will secure all or nothing, so the UI, the API, and the report would need a login. There is an item in their backlog that should address this by adding roll based access. https://github.com/fescobar/allure-docker-service/issues/128
See https://github.com/fescobar/allure-docker-service#enable-security for more information on native Allure security. 

In combination with the Allure security or if using basic auth, we will need to use GitHub Tokens and GitHub Secrets to run the send-results script form a GitHub action after a test execution.

**Comment by esune** [comment]
I am unable to self-assign this issue, but am going to start working on it FYI

**Comment by esune** [comment]
UI: https://allure-von.pathfinder.gov.bc.ca
API (protected): https://allure-api-von.pathfinder.gov.bc.ca

**Comment by esune** [comment]
Updated URLs:
UI: https://allure.vonx.io
API: https://allure-api.vonx.io

Services currently run in unprotected mode.

**Comment by esune** [comment]
Unless further work is required, this issue can be closed.
