### ISSUE TITLE
Check that the GHAs are running on Hyperledger organization and don't run if not

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#162]
Today, if a person forks the AATH repo, they GHActions run on their fork, but they shouldn't.  They can turn off the running of GHA, but they shouldn't have to do that.  Please add something (not sure where) to make sure that by default the jobs ONLY run from the hyperledger organization repo of AATH. 

Bonus point if there is a way that the fork can activate the running of the tests.

It may be that the tests have to run within a fork, but the tests could have a first line that detects the test is not running on Hyperledger account and exits.  The status could be "Pass", and it would quietly run everyday, or "Fail" and given instructions on how to block running the tests on the fork.

An alternative to all this would be to have a second repo that has the GHAs in it, and it just uses AATH to get the tests to be run.  That would mean that every fork of the AATH repo wouldn't have any GHAs and so wouldn't try to run them.

Open to ideas, but I think we need to fix this sooner than later.

**Comment by TimoGlastra** [comment]
I think the approach described here should work: https://github.community/t/do-not-run-cron-workflows-in-forks/17636/2

The action checks if it is in the expected repo (Hyperledger org) and also checks if the cron job triggered the action

This way the fork can still use the manual trigger option (using the web ui)

**Comment by swcurran** [comment]
Nice!  Thanks.
