### ISSUE TITLE
Suggestions for reorganizing the tags.

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#164]
I generated a list of the tags in use for all of the scenarios and found that we had about a 100.  I think we can reduce that significantly by dropping a number of them and replacing them with the following subsets.  See the notes associated with each group.

The effort for this issue should include the following:

- reset all the tags on the scenarios
- adjust the runset tags accordingly
- document the range of tags and how they are used.

## Tags for scenario ID (sequential, no meaning):

A tag for each scenario, whose only purpose is to be able to run just a test or two from the command line.

@t001

# Tags for Scenario Metadata:

A tag to convey something about the scenario. `@wip` is probably the most important, but a couple of others may be valuable.

@NeedsReview
@wip
@NegativeTest

## Scenario Coverage Tags:

A tag for each RFC and AIP specifically tested in a scenario -- excluding "underlying" RFCs that are covered in essentially every test.  For example, RFC0011 (decorators) is used (I think) in a lot of scenarios and so _might_ be a candidate to remove (or not...).

@RFC0011
@RFC0023
@RFC0036
@RFC0037
@RFC0160
@RFC0183
@AIP10
@AIP20

## Tags for Temporary Issues:

A tag tied to a specific issue that should be addressed at some point. It needs to reference the repo in which the issue resides.

@issue:https://github.com/hyperledger/aries-cloudagent-python/issues/418

## Tags on test variants:

A tag for scenarios that implement a variant of a test for (usually) a given RFC.

@Indy
@revocation
@delete_cred_from_wallet
@MultiUseInvite
@ProofProposal
@SingleTryOnException
@SingleUseInvite

**Comment by nodlesh** [comment]
Took a look at what is there. It seems that I would only be removing 4 tags dealing with priority. The rest are needed. The overall tag count isn't going to change all that much. Here are the updates that would be done.

Changes:
- Test IDs from @T001-AIP10-RFC0160 to @T001-RFC0160 (test ids need to be unique across all features so keeping the RFC number does that)

Removals:
- P1, P2, P3, P4 (These were the original priority categorization, these can be replaced with the Allure ones)
	- blocker, critical, normal, minor, trival must stay. They are used by Allure. 

Additions:
- @AIP10
- @AIP20

Tags to stay, but are not mentioned above:
- @AcceptanceTest - A functional test taken from directly from the language in the RFC
- @DerivedFunctionalTest - A functional test, not directly implied in the language of the RFC, but is inferred from the text
- @Schema_XXXX - This constrains the credential types allowed in the test scenario for external data driven tests.
- @ExceptionTest - A test that trys to force a documented exception mentioned in the RFC
	- How is this different from @NegativeTest? A Negative test try's to break software, do something malicious, or force an exception not mentioned in the RFC.

**Comment by swcurran** [comment]
Sounds good.

The only one I disagree with is this: `Test IDs from @T001-AIP10-RFC0160 to @T001-RFC0160 (test ids need to be unique across all features so keeping the RFC number does that)`

I think the unique ID should be just "@T001" and so on -- or whatever is needed to make them unique.  A single scenario might have multiple RFCs and I would like to be able to run all the scenarios for an RFC, so I think they should be handled separately and the same as "@AIP10" and "@AIP20" -- where I can have either or both (or none) on any scenario.

**Comment by nodlesh** [comment]
To be clear, when I mentioned keeping the rfc number on the test id, it wasn't at the sacrifice of the separate rfc tag RFC0160. I'd still prefer to keep that rfc number as part of the test id, so that one -t in the run command and run one test, and that the id, if that is all I see, can be a descriptor of where it belongs. 

To clarify what you are saying. Are you saying use two tags to run one test? 
for example, `.manage run -d acapy -t @T001 -t @RFC0160`
and `.manage run -d acapy -t @T001 -t @RFC0036`

or are you saying keep the IDs continually incremented across the protocol suites?
for example, the tests IDs end with T011 in the RFC0160, and begins with T012 in RFC0036
In this case you can run with one -t in the run command, but you can't tell off hand where the test belongs.

**Comment by swcurran** [comment]
My suggestion would be to run a specific test you do `.manage run -d acapy -t @T001`, where the "001" has no meaning other than it points to a specific test that may be in any test suite.  My thought is that , it would be used only when developing, and you are having trouble with a specific test.

If I cared about a particular RFC, I would use the `-t @RFC0023` mechanism.  And even `-t @RFC0036 -t @RFC0037 -t ~@revocation` to test all issuing and verifying that don't involve revocation.

**Comment by ianco** [comment]
I agree with @nodlesh regarding the format of the unique tags per test, i.e. something like `@T001-RFC0160` vs `@T001`

The problem with the simplified version of the tag is that it's more difficult to manage uniqueness across all the test scenarios (e.g. if I'm creating a new test, what do I call it?  I need to check all the tests across all the scenarios to figure out what number to use)

**Comment by nodlesh** [comment]
My final comment on this. If an id tag can be unique and at the same time be meaningful, why would we choose to have a tag that is unique and not meaningful? The only difference is 7 characters.

**Comment by swcurran** [comment]
My experience was that when I wanted to run just one test, I could just look at the test number and type it in on the command line (e.g. "-t t0027") vs. having to find and copy/paste the full tag.

However, I'm easy with it and leave it to what you think best.
