### ISSUE TITLE
Remove dependancy on Dummy Cloud Agent and Cargo

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#17]

**Comment by swcurran** [comment]
What's the context of this? Is this to try to eliminate the Cloud Agent from VCX?  I don't know that it is possible.  Or perhaps this came up in your discussion with @ianco?

**Comment by nodlesh** [comment]
@swcurran Just creating a new issue to triage before it gets into a backlog. Running through the test harness setup was wondering if the Dummy Cloud Agent and the Cargo could be removed and replaced with something else in python. That said I'm not exactly sure what the Dummy Cloud Agent does for us yet. If you are sure we can't remove this dependancy then we can close this issue. Otherwise, can we keep it in New Issues to triage. The backlog is sort of work we agree needs to be done, eventually. 
Ian and I will be meeting on Monday now.

**Comment by nodlesh** [comment]
Closing this issue. The Scope of this work right now is for ACA-Py agents. the Dummy Cloud Agent if for the vcx indy agent. So out of scope.
