### ISSUE TITLE
Verify that the RunningLocally.md file is still valid

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#170]
The content of the [RunningLocally.md](/RunningLocally.md) file appears to be pretty old and perhaps out of date.
Please review the file and see if it needs to be updated, altered or removed. If it is kept, reference should
be given in the section encouraging people not to use this to the text that (I'm pretty sure...) Timo did
about how to debug with AATH and Docker.﻿

**Comment by ianco** [comment]
I'll document for aca-py only, the VCX backchannel is out of date, but I can update to cover aca-py and the backchannel code itself.

**Comment by swcurran** [comment]
Thanks — not a high priority. Just something for your list.

**Comment by ianco** [comment]
OK upon some review I don't think it's possible (or at least not *easy*) to run the tests locally.  There are too many dependencies about the expected environment setup, number of agents to run etc, for running locally to provide any practical value.

I suggest we delete the "RunningLocally.md" file or edit it to simply say that running locally is not supported.

**Comment by swcurran** [comment]
Document has sufficient warnings.
