### ISSUE TITLE
acapy-dotnet results are empty in the most recent run

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#176]
The last run of the acapy-dotnet runset resulted in no tests being recorded in allure:

https://allure.vonx.io/allure-docker-service-ui/projects/acapy-b-dotnet/reports/27

That's the current "latest", but presumably that will change with today's run.﻿

**Comment by nodlesh** [comment]
Yes, I seen that this morning. Everything passed and the send looked successful, but nothing showing in allure. I've never seen that before. There is nothing different between that action and the others. Will dig deeper.

**Comment by swcurran** [comment]
Looks like it is fixed now.

**Comment by nodlesh** [comment]
Yes, I'll keep an eye on it.

**Comment by swcurran** [comment]
Closing.
