### ISSUE TITLE
Propagate Agent startup issues through to the backchannel startup if a problem arises

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#18]
AS A Aries Test Harness User, I want to know all aca-py issues on startup, SO THAT I can properly diagnose and rectify the issue.

- [ ] Propagate aca-py startup executions though to the backchannel startup routine.  

- [ ] print out either by default or as a debug message all the agents startup parameters.

**Comment by swcurran** [comment]
And to be more precise about this - backchannels should propagate start up errors to the Aries Test Harness.  Since the test harness can be used with any agent, it's not just an ACA-Py issue.

**Comment by nodlesh** [comment]
@swcurran Good point!

**Comment by swcurran** [comment]
I think this is well enough covered now.  Closing -- please reopen if it is still an issue.  If so, please provide more specifics on what's needed.

**Comment by nodlesh** [comment]
I'm not sure this goal is accomplished. If an agent fails to startup the reasons why and the errors are lost (especially when running with the manage script). We just get `waiting for agent to start` and if it never does it just times out. It would be nice for startup issues to be channeled to the backchannel so it can do something with those messages. The workaround now is after an agent fails to start, you have to manually run  docker command to start that agent separately from the manage script to see what the problem is.

**Comment by swcurran** [comment]
I'd say at most just document the issue.  If the agent fails to start, the timeout waiting notifies the user.  The pause and check for the tails server and the ledger are helpful as well at defining common problems.  Beyond those, the only real issue is when developing a backchannel, and for that, some guidance such as you mention in your comment is sufficient, I think.
