### ISSUE TITLE
Add reverse combinations of runsets and tag the "reverse" tests 

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#181]
Please add the reverse runsets, where (for each), the first Test Agent is ACME and Faber, the latter Bob

- AF-Go to ACA-Py
- AF-.NET to ACA-Py
- AFJ to ACA-Py
- AF-.NET to AFJ
- ACA-Py to AFJ to AF-.NET

In doing so, please tag the reverse the tests (e.g. where Bob initiates connections) so that they can be bypassed for some runsets where those features are not supported, and add the appropriate "-t" arguments to each runset.

**Comment by nodlesh** [comment]
The allure project names for the new runsets are as follows. 
- AF-Go to ACA-Py -> afgo-b-acapy
- AF-.NET to ACA-Py -> dotnet-b-acapy
- AFJ to ACA-Py -> javascript-b-acapy
- AF-.NET to AFJ -> dotnet-b-javascript
- ACA-Py to AFJ to AF-.NET -> acapy-b-javascript-f-dotnet

Let's be sure on these names before results are pushed to them. You cannot "modify" a project name in allure easily. You can delete and recreate, but that removes results history.
