### ISSUE TITLE
Aries Agent Test Harness determining Conformance with Aries Interop Profile 1.0 for Agent Builder

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#2]
AS AN Aries Agent Builder, I WANT to run a series of tests, SO THAT I can determine interoperability with other Aries Agents based on [Aries Interop Profile 1.0](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0302-aries-interop-profile)

#### Acceptance Criteria

**Scenario:** Agent Builder creates agent and gets conformance report
Given a ACA-Py Agent Builder has created a new agent
When they execute the [Aries Agent Test Harness](https://github.com/bcgov/aries-agent-test-harness)
Then they will get a report stating the level of conformance to the Aries Interop Profile 1.0.0

Note: The [aries-rfc 0270: Interop Test Suite](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0270-interop-test-suite#0270-interop-test-suite) States "The test suite isn't a compliance tool, and it should be unopinionated about what's important and what's not.”
~We agree that we are not aligning with this goal? Or are we using the term compliance in a different sense?~ This Test Harness determines "conformance" to a version of the AIP it is not labeling anything as compliant with a standard. 

**Scenario:** Agent Builder creates a backchannel adaptor for their agent instance (_This may need its own sub story instead of having it in the epic_)
Given a ACA-Py Agent Builder
And has created a new agent
When they use the Aries Agent Test Harness
And create a backchannel adaptor based on the interface provided
Then they will be able to execute the Aries Agent Test Harness suite of tests

**Scenario:** Usage in Pipelines (_Maybe move into its own Epic_)
**Scenario:** Usage for Devs (_Maybe move into its own Epic_)
**Scenario:** Usage for P2P Interop (_Maybe move into its own Epic_)

**Comment by swcurran** [comment]
While the test harness is not a compliance tool, we can use it to represent conformance. We can do this by indicating a set of test cases that are relevant in a context, and in the case of the test harness, defining a "golden" agent to test against.  So I don't think it's against that particular line in the RFC.

Note that the test harness is just for conformance.  It just happens to be our first target.  It's also for pipelines, devs, and peer-to-peer interoperability.

Make sense?

**Comment by nodlesh** [comment]
@swcurran Yes makes sense. I like the word conformance, it is slightly softer and less strict than compliance. I think I'll change the wording in this story to make it clear and maybe align more with RFC 0270. I'll also add more Acceptance Criteria for pipelines, devs, and p2p. Thanks.
