### ISSUE TITLE
Change the handling of the ./manage "-t" parameters to be passed to behave as a single parameter

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#213]
**User Story**: As a tester, I would like to be able to pass tag parameters through to `behave` that might include spaces so that I can be very precise in selecting the tests to be run.

Currently, we are passing each `./manage run` "-t" parameter as an individual "-t" parameter to behave.  The passing of the data through multiple layers of shells makes it very hard (impossible?)  to pass in spaces -- I've tried.  I'm thinking that if we adjusted the ./manage script to NOT insert the "-t" for each parameter, but rather to just assemble the list of parameters, we can pass them to behave as a single `-t "${list+ of_t_args}"`. That would always us to do ANDs and ORs between the tags to get the right combinations.

Calls for experimentation...

**Comment by nodlesh** [comment]
@swcurran Does this construct that works with AATH solve the problem this issue was meant to fix? 

```
-t @RFC0023,@T001.1-RFC0036,@RFC00453,@RFC00454 -t ~@wip -t ~@T003-RFC0023 -t ~@T004-RFC0023  -t ~@T005-RFC0023 -t ~@T006-RFC0023 -t ~@CredFormat_JSON-LD
```

Stringing tags together in one `-t` with commas as separators is equivalent to an `OR`. The separate `-t` options is equivalent to an `AND`.

**Comment by swcurran** [comment]
Yes -- sounds good.  Closing.

**Comment by nodlesh** [comment]
I'm updating the docs for running tests to explain this.

**Comment by swcurran** [comment]
Good stuff -- thanks!
