### ISSUE TITLE
Update AFJ backchannel to run on main branch

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#251]
Currently the AFJ backchannel has a packaged version of AFJ, meaning it is not testing against the latest code.

There were quite some changes in the framework since last updated so probably also needs some updates to the backchannel code.

- [ ] Update the AFJ backchannel to work with the current code in the main branch of AFJ
- [ ] Update `Dockerfile.javascript` to use the currently released version of AFJ on NPM
- [ ] Add `Dockerfile.javascript-main` to clone and use the main branch of AFJ (see ACA-Py implementation)
- [ ] Update the github action workflows to use the `Dockerfile.javascript-main` instead of `Dockerfile.javascript`

**Comment by TimoGlastra** [comment]
@blu3beri I can't assign you, but can you pick this one up?

**Comment by berendsliedrecht** [comment]
> @blu3beri I can't assign you, but can you pick this one up?

Yes, will do!
