### ISSUE TITLE
Add tests with JSON-LD specific data

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#256]
Current Issue Credential (and Present Proof tests I'm working on now) make use of the same custom drivers license schema used for indy tests. I think it will be good to add tests (credential and proof data) specific to JSON-LD credentials that leverages the public available contexts.

Some contexts we could use:
- [Traceability Vocabulary](https://w3c-ccg.github.io/traceability-vocab/)
- [Vaccination Vocabulary](https://w3c-ccg.github.io/vaccination-vocab/)
- [Citizenship Vocabulary](https://w3c-ccg.github.io/citizenship-vocab/)

**Comment by ianco** [comment]
FYI I'm updating the alice/faber demo to use the Citizenship vocab to support json-ld credentials and proofs, and will also be adding this to the aca-py integration tests.

**Comment by TimoGlastra** [comment]
Awesome. Do you already have some example documents I can re-use?

**Comment by ianco** [comment]
> Awesome. Do you already have some example documents I can re-use?

Work in progress is on this draft PR:  https://github.com/hyperledger/aries-cloudagent-python/pull/1235

I've added a more detailed tutorial document (wip) to provide some more detailed cred/proof examples:

https://github.com/hyperledger/aries-cloudagent-python/pull/1235/files#diff-5a4a5e5fa63814bb4f57173307b734dbaa0742849534bb5a8219de1f90ce8e7e

**Comment by TimoGlastra** [comment]
Nice.

I see you also have an example with the vaccination vocab. It's not working ATM in ACA-Py, I'm running into an issue with compaction: https://github.com/w3c-ccg/vaccination-vocab/issues/22

**Comment by ianco** [comment]
> Nice.
> 
> I see you also have an example with the vaccination vocab. It's not working ATM in ACA-Py, I'm running into an issue with compaction: [w3c-ccg/vaccination-vocab#22](https://github.com/w3c-ccg/vaccination-vocab/issues/22)

Right, I don't have this example working yet either, it's on my to-do list once I finish updating the alice/faber/bdd with the citizenship example.

**Comment by TimoGlastra** [comment]
@ianco https://github.com/hyperledger/aries-cloudagent-python/pull/1252 should fix the issues with vaccination vocab

**Comment by swcurran** [comment]
Closing -- I think we are good with the samples we have today.
