### ISSUE TITLE
Auto Response State Handling 

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#268]
As an Aries Framework Interop Tester I want to test my auto responding agent in the AATH, so that auto responding agents can be verified for interop along side other auto responding agents or non-auto responding agents with the same tests. 

**Problem:** The tests as they stand check transitional protocol states as stated in the RFC for the connection protocols (and other protocols as well). With auto responding agents (like Verity), the requests are responded to automatically and the agent protocol states transition to a further state in the process than the tests expect them to be in. IE. When the invitee sends a connection request, the inviter may auto respond. The test expects the state to be `requested` but both agents have already moved onto `responded`. This causes the connection test to fail, however both agents have been successful thus far. 

**Solutions (Proposals):**

1. No transitional state checks in connection tests. It may be overkill for the AATH to be checking all of the interim states in the protocols. Though the RFCs state these are the states after the given operations, the overarching goal of the AATH is to facilitate interop testing between agents of differing capabilities. In this case, kicking off the protocol, loosely driving the intermediate operations, and then checking that the final state of the protocol is correct, should suffice to accomplish the AATH goal. 

2. There is some value in checking the intermediate states as it relates to failing the test at the appropriate time when an error happens, which would be useful in backchannel development and debugging. Also capturing the expressed description in the RFCs. If we want to keep this benefit it is proposed to amend a response from the backchannel to the test harness with `transitioned_states`. The `state` still represents the current state of the agent in the protocol, but if the state is not expected from a non-auto respond perspective, the test harness can check the transitioned_states and determine that we are working with an auto responding agent, pass the step if the transitioned states include the current expected state and make decisions on the remaining steps to run. 
```
{
   "state":"responded",
   "transitioned_states":[
      "invited",
      "requested"
   ]
}
```

3. Require the backchannel to implement a webhook to return each transitional state as it comes in.

**Chosen Solution:**
The community seems to be leaning toward option 1. Given that, the proposal is to create a new version of the connection test step definitions that do not check intermediate protocol states. It will only check for 200 response codes to carry on. These new step definition will supplant the old ones once we are sure we are not negatively impacting other agents with existing backchannels already running these tests.

**Comment by smithbk** [comment]
I agree with solution 1.  This is the simplest solution for backchannels and it adequately tests for pass/fail status for each protocol.  I actually had to enhance my agent to try to meet this need of stepping through transitional states, potentially destablilizing my agent.  So we don't want to require that.

Also, I think from a debugging perspective, if there is a failure, then we will likely just be looking at logs of the two agents anyway.  Knowing more about what transitional state an agent was in when it failed the test doesn't help much.

**Comment by nodlesh** [comment]
There is another consideration when it comes to ease of Backchannel development. With option 1, the backchannels are still going to have to handle the calls from the test harness dealing with sending responses even though the auto response happened. The backchannels will still have to return a response code of 200. The tests will still make calls but checks for states will be removed. 

However, with option 2, once a list of transitioned states are returned, the test harness can make decisions based on that fact and not make any operation calls to the backchannel to respond to. Therefore, the backchannels wouldn't need handlers for operation it doesn't use. It may be less effort to return transitioned states than it would be to write handlers for unused operations. 
The tests would look something like this.
```
@when('"{invitee}" sends a connection request to "{inviter}"')
    .
    .
    (resp_status, resp_text) = agent_backchannel_POST(invitee_url + "/agent/command/", "connection", operation="accept-invitation", id=invitee_connection_id)
    assert resp_status == 200, f'resp_status {resp_status} is not 200; {resp_text}'

    if "responsed" in resp_text['transitioned_states']:
        context.auto_responded = True
    else:
        # get connection and verify status
        assert expected_agent_state(invitee_url, "connection", invitee_connection_id, "requested")


@given('"{inviter}" receives the connection request')
    .
    .
    if context.auto_responded:
        pass
    else:
        # inviter already recieved the connection request in the accept-invitation call so get connection and verify status=requested.
        assert expected_agent_state(inviter_url, "connection", inviter_connection_id, "requested", wait_time=60.0)


@when('"{inviter}" sends a connection response to "{invitee}"')
    .
    .
    if context.auto_responded:
        pass
    else:
        .
```

**Comment by nodlesh** [comment]
I am now thinking we can do a combination of both option 1 and 2. The backchannels can still return states for the operations it supports. The states are not used for comparison to an expected state, but just to make decisions on bypassing other operations. So instead of transitional states, the test harness just check the current state and if it is responded, then assumes auto_responded and bypasses the responding operations.

**Comment by Matt-Spence** [comment]
Do we know that agents which auto respond in protocols will end up in the same state? Some agents might auto respond for fewer steps. If you want this to be specific to the connection protocol then it seems fine, but if this is intended to be applied to other protocols then we might want to make it more general, such as by keeping a list of the expected states in order and checking if the returned state is further up the list than the expected state

**Comment by swcurran** [comment]
I'm good with the best change that doesn't require changing the agent.  Don't want to require that!  I'm not deep enough into the implementation to understand what's best, but I think @nodlesh 1/2 solution sounds good.  It would be good if this can be applied to other protocols as needed.

@Matt-Spence -- it sounds like there is a mix.  ACA-Py has an "auto-" mode for a number of operations, but those are generally only used for development, as in production we generally want the controller to make all the decisions -- even the controller's decision is always a "Go For It!".  But from @smithbk 's note above, it sounds like their agent is auto-connecting as well.

**Comment by Matt-Spence** [comment]
@swcurran That's the impression I'm getting as well. @nodlesh I also think the combination solution sounds best

**Comment by smithbk** [comment]
Combination solution sounds good to me ... thanks
