### ISSUE TITLE
Testing Mediation in AATH

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/owl-agent-test-harness#272]
With support for mediation in AIP 2.0 we need a way to test mediation with AATH.  There are several ways we could do that.  This issue is to generate conversations about that the best way to do that.

In AIP 2.0 Mediation is an optional feature, and has three elements that are worthy of interoperability testing:

* being a mediator (optional for AIP 2.0)
* using a mediator (mediator client) (optional for AIP 2.0)
* interacting with another agent that is using a mediator (necessary for AIP 1.0 and 2.0) -- should be a slam dunk :-)

The use or not of a mediator with any specific Test Agent does not need to impact any test case, as it is essentially invisible to the test suite.  It's more a question of how the Test Agent (backchannel + Component Under Test) is set up.  The biggest challenge I see is how to report that a Test Agent passed the steps of being a mediator client or interacting with an agent using a mediator.

Here are a couple of the options that I can see we could implement:

1. To test mediators (e.g. ACA-Py deployed as a mediator), define a standard containerized mediator that can be spun up as a service. Anyone with a mediator could create a dockerfile format that produced a container image with their mediator configured and ready to go. At runtime, the test executor could start up one of the available mediator services.

2. Per run, a config parameter could be passed in when starting a test run to indicate that a mediator is available. for the Test Agents to use. Backchannels that wanted to demonstrate support for being a mediator client could use the mediator.  They would (somehow) report to the Test Harness whether or not they were using the mediator or ignoring it.

3. Test Agents docker (container) images could be constructed to include a mediator in them, rather than as an outside service. There use of the mediator could be invisible to the rest of the Test Agents (although the other Test Agents would have to interact with the mediator if used).

4. We could use 1+2 or 3 and  have specific tests that required the use of mediation by the Test Agent and checked that it was used. Backchannels that supported mediation could do so, using mediation for at least those specific tests (and perhaps always).

Other ideas?

@JamesKEbert @nodlesh @ianco @smithbk @TelegramSam @dbluhm @burdettadam

**Comment by TimoGlastra** [comment]
I'm really interested to see this added to AATH!

I think my preference would be to go for option 3 + 4. I think making it another service will make the already large matrix of services to test against each other even larger.

We could then write tests specific to the mediation coordination protocol and also use existing tests but with mediation enabled (e.g. like `@DIDExchangeConnection` but then `@MediationConnection`)

**Comment by ianco** [comment]
Agree with @TimoGlastra 's comments

**Comment by nodlesh** [comment]
- Leaning toward 1 and 4. I don't see a reason to not have the mediator as a separate containerized service. Agents that support mediation can start up with a different flag on the run command.  `-d javascript -b acapy-main -F acapy-main` where `-F` is Faythe/Mediator. Why conceal the mediator?
- If the goal is to test interoperability with mediators then the test harness should know about it. If nothing else to make it obvious in the test reports. Maybe even to the level of assigning the role in the scenario role table at the beginning of each test.
```
Given "3" agents
      | name    | role   |
      | Acme    | issuer |
      | Bob     | holder |
      | Faythe  | mediator |
```
- There could be a Mediation test suite for establishing Mediators. Then that set of steps can be used in other tests not unlike DID Exchange and Connection reuse. This could be used as Timo mentioned with @Mediation tags.

**Comment by ianco** [comment]
> Why conceal the mediator?

The advantage of concealing the mediator is that you can re-run the entire test suite with or without the mediator.  This is the approach we take in the aca-py BDD tests.  We don't need any extra tests, we just run the set of tests: with a mediator; with multitenancy; with mutitenancy *and* a mediator; etc etc.

You just need a flag you can pass to the backchannel to tell it to startup a mediator in addition to the regular agent.

**Comment by nodlesh** [comment]
Is it the case that an Aca-py agent, for example, will always use an Aca-py mediator? Wouldn't it be test worthy to see if an agent of one Aries framework could use a mediator from another framework? If so, a separate mediator service would facilitate that.

**Comment by nodlesh** [comment]
#427 closes this issue.
