### ISSUE TITLE
Javascript Agent Randomly failing to receive message from Aca-py on connection accept-invitation

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#282]
When running any test with Javascript as Acme and Aca-py as Bob, the establishment of a connection is not guarenteed. Randomly (probably a timing issue), when Aca-py send a `connection/accept-invitation`, the Javascript agent throws this error:
```
[2021-07-08T18:57:44.611] [INFO ] [TSED] - received agent message {}
(node:29) UnhandledPromiseRejectionWarning: IndyError: CommonInvalidParam3
    at Object.callback (/src/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``` 

I am unsure of why this happens and why it doesn't seem to error out at other runs. The test that I can get it to happen almost all the time when debugging in VSCode is T001-RFC0036. Running the tests with the manage script at the command line may or may not produce the same problem at the same point in the test suite. 

Not sure if it has something to do with the merge of #255? The day after this merge is when the problem started to appear. 

@TimoGlastra maybe you can get a chance to take a look at what might be going on here?

**Comment by TimoGlastra** [comment]
The backchannel is using an old version of AFJ. I think we can best update the backchannel first and see if the problem is resolved
