### ISSUE TITLE
Auto Responding version of Acapy GHA Test Runset

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#325]
With the support of Auto Responding in Issue Credential and Present Proof in AATH, it may be advisable to create 1-n daily git hub action runsets that have all or a combination of auto-respond flags enabled when running acapy.  

To facilitate this, there are two approaches that have been discussed. More alternatives are welcome. 
1. Make a new image for acapy names something like `acapy-auto`. So executing the tests with auto enabled would look like this `./manage build -a acapy-auto` and `./manage run -d acapy-auto -t ...`
2. Add the ability to pass a configuration file to the build command. `./manage build -a acapy-main -config AcapyAutoEnabled`

**Comment by swcurran** [comment]
I don't think the auto-config settings should be relevant for the test suite. At most it should be buried in the backchannel.  I'm going to close this. Please reopen if you think we still need to do this.
