### ISSUE TITLE
Test Suite Execution/Conformance Result Public Links

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#4]
AS AN Agent Builder, I WANT to know what the test suite results are for my agent based on a Aries Interop Profile version, SO THAT I can link the results in the AIP RFC where my Aries Agent is listed.

### Acceptance Criteria
**Scenario:** Agent Builder add a link to Test Suite results for the Aires Agent
Given an Agent Builder who has created an Aries Agent
When they execute a test suite related to the AIP version
Then they will see the results of the test suite 
And be provided a public link to use for future reference

**Comment by swcurran** [comment]
This is sufficiently covered by the aries-interop.info site for now.
