### ISSUE TITLE
Admin API on Aca-py Issue Credential intermittently give 500 Internal server errors

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#56]
### Issue
The following Gets and Posts through the Admin API for Issue Credential (AIP 1.0) will intermittently throw a 500 internal server error, some Gets (for the webhooks) even need a sleep() before the call in the test harness to make the call work, even though there are sleeps and wait loops in the backchannel. 

All of these examples are from the 0036-Issue-credential.py step implementation. 

**Store in the "Holder acknowledges the credential issue" step**
(resp_status, resp_text) = agent_backchannel_POST(holder_url + "/agent/command/", "issue-credential", operation="store", id=context.holder_cred_ex_id, data=credential_id)

**Get data from web hook in the "Holder Requests the credential" step**
sleep(1) 
(resp_status, resp_text) = agent_backchannel_GET(context.issuer_url + "/agent/response/", "issue-credential", id=context.cred_thread_id)

** Get data from web hook in the "Issuer Offers a credential" step**
sleep(1) 
(resp_status2, resp_text2) = agent_backchannel_GET(context.holder_url + "/agent/response/", "issue-credential", id=context.cred_thread_id)

Sometimes removing the sleep(1) from some of the Gets will trigger a 500 on the next post. For example, not sleeping on (resp_status, resp_text) = agent_backchannel_GET(context.issuer_url + "/agent/response/", "issue-credential", id=context.cred_thread_id)
may cause a 500 on this Post, (resp_status, resp_text) = agent_backchannel_POST(issuer_url + "/agent/command/", "issue-credential", operation="issue", id=context.issuer_cred_ex_id, data=credential_preview)

### Outcome
500 Internal Server Error\n\nServer got itself in trouble

### Expected Outcome
A successful call or an error explaining the exact issue if its timing related or otherwise.

### Workaround
Putting in the sleep(1) in the test harness seems to work for most calls, though it will occasionally still happen on Posts. 

### Other Information
I have not seen this happen when just running the tests through manage run. It will happen more when the agents are started and left running like while developing tests or debugging. Also note these 500 errors will not happen when stepping through code. 
This does not happen with the Connection Protocol

### Test Cases Affected
T001-API10-RFC0036
T002-API10-RFC0036
T003-API10-RFC0036
T004-API10-RFC0036

### Severity
Medium
### Business Priority 
Medium

**Comment by swcurran** [comment]
@nodlesh -- is this still an issue or can we close?

**Comment by nodlesh** [comment]
This issue is not currently reproducible. That said, it was an intermittent issue at the time. Closing this now, and will remove the sleep calls and watch for future cases of this issue. If it raises its head again, we can log another issue.
