### ISSUE TITLE
python backchannels differentiate between routes with and without trailing slash

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#68]
Took me a while to figure out the requests to the python backchannels differentiate between routes with and without trailing slashes.

e.g. GET `/agent/command/connection` returns 404 not found
while GET `/agent/command/connection/` returns 200 with all connections.

This seems like unexpected behaviour to me.

**Comment by swcurran** [comment]
At minimum, we need to get that into the docs.  How did you find that -- e.g. what were you doing?  I'd think the Test Harness would make those calls, and it would be the backchannel responding?

**Comment by TimoGlastra** [comment]
Maybe not the most common use case. I'm running the acapy backchannel while developing the .NET endpoints to check what is expected and returned. During this i'm logging the endpoints in a Postman collections for later reference. Once we have a swagger definition this won't be necessary anymore.

Because the backchannel is only called by the test client i'm not suggesting to change the current behaviour. More as a heads up as i've never encountered this before.

**Comment by TimoGlastra** [comment]
Fixed in #69
