### ISSUE TITLE
correctly log ACA-Py logs to log file

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#85]
In https://github.com/bcgov/aries-agent-test-harness/pull/81 I made some changes to the ACA-Py backchannel to also log the ACA-Py logs. However after using it for a while it doesn't seem to work correctly.

For context: this pr persists the logs of all containers (using `docker logs`) to files in the `.logs` folder.

However only the backchannel logs (not the ACA-Py logs) are written to their corresponding log file (e.g. `.logs/acme_agent.log`.  As I'm pretty unfamiliar with Python I'm certain I messed something up. @ianco @nodlesh could you maybe take a look or point me in the right direction if you have the time?

As a side note: would it be possible to add a param to print the logs without color when using a non interactive shell or something? The logs are a bit hard to read with the color escaping characters:
```
[0m[?7h[0;35mPassing payload to handler handle_connections payload is: {"accept": "manual", "created_at": "2020-08-03 13:04:39.742471Z", "connection_id": "915086c2-2515-49ee-af7c-1c6707d3c33a", "state": "invitation", "their_label": "dotnet", "initiator": "external", "invitation_key": "MRZsFpyVZ4HHCzkr4VF4sPodjgB5cNpEi8PQgFZr6gi", "routing_state": "none", "updated_at": "2020-08-03 13:04:39.742471Z", "invitation_mode": "once"}[0m
[0mListening to backchannel on port 9030
Listening to web_hooks on port 9033
```

**Comment by ianco** [comment]
Looking into this one ...  When I run locally, the aca-py logs show up after I eXit the backchannel, but they don't show up in the docker logs.  

Will continue to look into this ...

**Comment by ianco** [comment]
Looks like the code isn't picking up the subprocess (aca-py) output until the subprocess exits.  So, if you run interactively, then when you e"X"it you get the logs.  When you run docker, the subprocess never ends (the docker gets cancelled) so you never get the log output.

I don't know why this is working differently in the alice/faber demo, it looks to me like the same code :-(

**Comment by TimoGlastra** [comment]
Alright that's a bummer.

Thanks for trying.

**Comment by swcurran** [comment]
Closing for now.  Nice to have in the future, but we'll leave as is for now.
