### ISSUE TITLE
use requested_attributes instead of requested_values

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#87]
When the AATH client sends a `proof/send-request` operation to a backchannel it uses `requested_values` as attribute key for the requested attributes. However the Indy API's expect this to be `requested_attributes`.

I now see the ACA-Py backchannel transforms this parameter before sending it to ACA-Py. I know AATH is not Indy specific, but when another format than Indy will be used the whole `request_presentations~attach` will be different, so I think it will be easier to just use `requested_attributes`.

Maybe I'm missing something here?

Example:

```jsonc
{
   "connection_id":"<<connection_id>>",
   "presentation_proposal":{
      "@type":"did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/request-presentation",
      "comment":"This is a comment for the request for presentation.",
      "request_presentations~attach":{
         "@id":"libindy-request-presentation-0",
         "mime-type":"application/json",
         "data":{
            "requested_values":{ // --> change to `requested_attributes`
               "attr_1":{
                  "name":"attr_1",
                  "restrictions":[
                     {
                        "schema_name":"test_schema",
                        "schema_version":"1.0.0"
                     }
                  ]
               }
            }
         }
      }
   }
}
```

**Comment by swcurran** [comment]
Sounds right to me.  @nodlesh -- can you please take a look?  Thanks.

**Comment by nodlesh** [comment]
Sure, we can change it back to requested_attributes. I thought people would be translating the indyism anyway so I left it, but if it's easier then I agree.

**Comment by swcurran** [comment]
Yes - that part will only be used by Indy.  The split between indy and non-indy will be at the "request_presentations~attach" level. Perhaps all of that information should be included in the externalized data?
