### ISSUE TITLE
Finish Connectionless Proof Test Scenario(s) to AATH

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#90]
This was attempted in Aug 2020. There is code in the AATH to make this work. In submission related to this issue. It was determined that Acapy at the time did not support the connectionless scenario is played as the prover. This work has been put on hold until Acapy has this fully implemented. 

The main Story for this work was #11.

**Comment by TimoGlastra** [comment]
I'm curious how connectionless proofs will work in AATH. Will these be separate operations or the same operations, but the connection_id swapped with something else?

And is there anything I can do on the .NET side to leave it "Connectionless Ready"?

**Comment by TimoGlastra** [comment]
I'm currently working on integrating connectionless into AATH but only for usage with out of band (the AIP 2 approach). I see there's some foundation made for connectionless using AIP 1.0, but as it seems this has never run. 

@nodlesh I don't suspect anyone will implement connectionless anymore for AIP 1.0, so is it okay if I remove this in favour of the AIP 2 implementation (there is some overlap, but it's minimal)?

**Comment by nodlesh** [comment]
Yes,I agree that implementing AIP2 over AIP1 is the right way to go here. If we have a requirement for AIP1 with connectionless we will address it at that time.
